apiVersion: v1
kind: PersistentVolume

metadata:
  name: nfs-pv01
  namespace: test
  labels:
    pv: nfs-pv01
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  # recycle : delete pvc, will delete pv | Retain : delete pvc, will keep pv
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /nfs/share/pv01
    server: 44.208.119.243
---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: nfs-pvc01
  namespace: test
  labels:
    pv: nfs-pvc01
spec:
  resources:
    requests:
      storage: 500Mi
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      pv: nfs-pv01
---
apiVersion: v1
kind: Pod

metadata:
  name: web
  namespace: test
  labels:
    app: web
spec:
  nodeName: node-1
  containers:
    - name: web
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          hostPort: 8080
      volumeMounts:
        - name: workDir
          mountPath: /usr/share/nginx/html
  volumes:
    - name: workDir
      persistentVolumeClaim:
        claimName: nfs-pvc01

