# docker -v []
apiVersion: v1
kind: Pod

metadata:
  name: busybox
  namespace: test
  labels:
    app: busybox
spec:
  nodeName: node-1
  containers:
    - name: web
      image: nginx
      ports:
        - containerPort: 80
          hostPort: 8080
      volumeMounts:
        - name: workDir
          mountPath: /usr/share/nginx/html
  volumes:
    - name: workDir
      hostPath:
        # DirectoryOrCreate | File | FileOrCreate | Socket | ""
        type: Directory
        path: /workDir