apiVersion: v1
kind: Secret
metadata:
  name: testsecret
  namespace: test
  labels:
    secret: testcm
type: Opaque
data:
  db_name: dGVzdGRiMgo=
  db_host: MTI3LjAuMC4yCg==
---

# mount data in configMap into containers
apiVersion: v1
kind: Pod

metadata:
  name: busybox
  namespace: test
  labels:
    app: busybox
spec:
  nodeName: node-1
  containers:
    - name: web
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          hostPort: 8080
      volumeMounts:
        - name: workDir
          mountPath: /usr/share/nginx/html
  volumes:
    - name: workDir
      secret:
        secretName: testcm
        optional: true

