# mount pod defined information(metadata) into container
apiVersion: v1
kind: Pod

metadata:
  name: busybox
  namespace: test
  labels:
    app: busybox
spec:
  nodeName: node-1
  containers:
    - name: web
      image: nginx
      ports:
        - containerPort: 80
          hostPort: 8080
      env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      volumeMounts:
        - name: workDir
          mountPath: /usr/share/nginx/html
  volumes:
    - name: workDir
      downwardAPI:
        items:
          - path: podname.html
            fieldRef:
              fieldPath: metadata.name
