# Cache Data, help containers share data
# but if delete the pod, the emptyDir will disappear at the same time
# define an initContainer -> download data from initContainer to emptyDir ->
# mount the emptyDir to Container, show the shared data
apiVersion: v1
kind: Pod

metadata:
  name: busybox
  namespace: test
  labels:
    app: busybox
spec:
  nodeName: node-1
  initContainers:
    - name: download
      image: busybox
      command:
        - wget
        - -O
        - /workDir/index.html
        - https://www.baidu.com
      volumeMounts:
        - name: workDir
          mountPath: /workDir
  containers:
    - name: web
      image: nginx
      ports:
        - containerPort: 80
          hostPort: 8080
      volumeMounts:
        - name: workDir
          mountPath: /usr/share/nginx/html
  volumes:
    - name: workDir
      emptyDir: {}