apiVersion: v1
kind: Pod

metadata:
  name: busybox
  namespace: test
  labels:
    app: busybox
spec:
  nodeSelector:
    "app": "test"
  tolerations:
    -key: "app"
    value: "test"
    operator: "Equal"
    effect: "NoSchedule"
#    tolerationSeconds: 100
  containers:
    - name: busybox
      image: busybox

